name: Rust
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  LD_LIBRARY_PATH: ''

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Fmt
      run: nix develop --impure --command cargo fmt -- --check
    - name: Lint
      run: |
        rm -rf ~/.cargo/bin/
        nix develop --impure --command cargo clippy -- -D warnings
    - name: Build
      run: |
        nix build '.#'
    - name: Test
      run: |
        rm -rf ~/.cargo/bin/
        nix develop --impure --command cargo test --verbose
    - name: Audit
      run: |
        rm -rf ~/.cargo/bin/
        nix develop --impure --command cargo test --verbose
