name: Rust CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Fmt
      run: cargo fmt -- --check
    - uses: Lint
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Audit
      run: cargo test --verbose
