name: Rust
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fmt
      run: nix develop --impure --command cargo fmt -- --check
    - name: Lint
      run: nix develop --impure --command cargo clippy -- -D warnings
    - name: Build
      run: nix develop --impure --command cargo build --verbose
    - name: Test
      run: nix develop --impure --command cargo test --verbose
    - name: Audit
      run: nix develop --impure --command cargo test --verbose
